version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring_network
  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./json_exporter.yml:/etc/json_exporter/config.yml
    command:
      - '--config.file=/etc/json_exporter/config.yml'
    ports:
      - "7979:7979"
    networks:
      - monitoring_network

networks:
  monitoring_network: